# Generated by Django 5.2 on 2025-05-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlzheimersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('ethnicity', models.CharField(blank=True, max_length=50)),
                ('education_level', models.IntegerField(help_text='Years of education')),
                ('bmi', models.FloatField(verbose_name='BMI')),
                ('smoking', models.BooleanField(default=False)),
                ('alcohol_consumption', models.CharField(blank=True, max_length=20)),
                ('physical_activity', models.CharField(blank=True, max_length=20)),
                ('diet_quality', models.CharField(blank=True, max_length=20)),
                ('sleep_quality', models.CharField(blank=True, max_length=20)),
                ('family_history_alzheimers', models.BooleanField(default=False)),
                ('cardiovascular_disease', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('depression', models.BooleanField(default=False)),
                ('head_injury', models.BooleanField(default=False)),
                ('hypertension', models.BooleanField(default=False)),
                ('systolic_bp', models.IntegerField(verbose_name='Systolic BP')),
                ('diastolic_bp', models.IntegerField(verbose_name='Diastolic BP')),
                ('cholesterol_total', models.FloatField()),
                ('cholesterol_ldl', models.FloatField(verbose_name='LDL Cholesterol')),
                ('cholesterol_hdl', models.FloatField(verbose_name='HDL Cholesterol')),
                ('cholesterol_triglycerides', models.FloatField()),
                ('mmse', models.IntegerField(verbose_name='MMSE Score')),
                ('functional_assessment', models.IntegerField()),
                ('memory_complaints', models.BooleanField(default=False)),
                ('behavioral_problems', models.BooleanField(default=False)),
                ('adl', models.IntegerField(verbose_name='Activities of Daily Living Score')),
                ('confusion', models.BooleanField(default=False)),
                ('disorientation', models.BooleanField(default=False)),
                ('personality_changes', models.BooleanField(default=False)),
                ('difficulty_completing_tasks', models.BooleanField(default=False)),
                ('forgetfulness', models.BooleanField(default=False)),
                ('prediction', models.CharField(blank=True, max_length=20)),
                ('prediction_probability', models.FloatField(blank=True, null=True)),
                ('actual_diagnosis', models.CharField(blank=True, choices=[('Positive', "Alzheimer's Positive"), ('Negative', "Alzheimer's Negative"), ('MCI', 'Mild Cognitive Impairment')], max_length=10, null=True)),
                ('doctor_in_charge', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Alzheimer's Data",
                'verbose_name_plural': "Alzheimer's Data",
            },
        ),
    ]
