# Generated by Django 5.2 on 2025-05-06 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alzheimersdata',
            name='doctor_in_charge',
        ),
        migrations.RemoveField(
            model_name='alzheimersdata',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='alzheimersdata',
            name='patient_id',
        ),
    ]
