# Generated by Django 5.2 on 2025-05-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_remove_alzheimersdata_doctor_in_charge_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlzheimersData',
        ),
    ]
