# Generated by Django 5.2 on 2025-05-09 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ml', '0003_delete_alzheimersdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Age', models.IntegerField()),
                ('Gender', models.IntegerField()),
                ('Ethnicity', models.IntegerField()),
                ('EducationLevel', models.IntegerField()),
                ('BMI', models.FloatField()),
                ('Smoking', models.IntegerField()),
                ('AlcoholConsumption', models.IntegerField()),
                ('PhysicalActivity', models.IntegerField()),
                ('DietQuality', models.IntegerField()),
                ('SleepQuality', models.IntegerField()),
                ('FamilyHistoryAlzheimers', models.IntegerField()),
                ('CardiovascularDisease', models.IntegerField()),
                ('Diabetes', models.IntegerField()),
                ('Depression', models.IntegerField()),
                ('HeadInjury', models.IntegerField()),
                ('Hypertension', models.IntegerField()),
                ('result', models.BooleanField()),
                ('probability', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
